version: '3.7'

services:
  db-test:
    image: postgres:13.0
    env_file:
      - .env
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: mc:tests
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_HOST: db-test
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SETTINGS_MODULE: mc.settings
    entrypoint:
      - invoke
      - wait-for
      - db-test:5432
      - test
    depends_on:
      - db-test
    volumes:
      - .:/mc/
