FROM python:3.9-slim-buster
LABEL maintainer="GeeksCAT <info@geekscat.org>"

WORKDIR /mc/

RUN apt-get update \
    && apt-get install --no-install-recommends -qy wait-for-it \
    && rm -rf /var/lib/apt/list/*

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false
RUN poetry install

COPY . .